#!/bin/bash
# wrap vim
# export useful environment variables

export REPO_ROOT=$(2>/dev/null git rev-parse --show-toplevel)
export REPO_NAME=$(2>/dev/null basename "$REPO_ROOT")
export REPO_BRANCH=$(2>/dev/null git rev-parse --abbrev-ref HEAD)

command vim "$@"

unset REPO_ROOT
unset REPO_NAME
unset REPO_BRANCH
