#!/bin/bash
# cat a_script

if [ $# -ne 1 ]; then
  echo 'usage: cat <a_script>'
  return 1
fi

if . "$A_CORE/_get_a_script" "$1"; then
  cat "$_a_script"
else
  echo "a_cat: $1: No such file" >&2
  return 1
fi
