#!/bin/bash
# cat all files
# example:
# catall txt

if [ $# -ne 1 ]; then
  echo 'usage : catall <extension>'
  return 1
fi

find . -name "*.$1" -exec echo catall {}: \; -exec cat {} \; -exec echo \; | less -p "^catall"
