#!/bin/bash
# cp a_script

if [ $# -ne 2 ]; then
  echo 'usage: cp <from> <to>'
  return 1
fi

if . "$A_CORE/_get_a_script" "$1"; then
  cp -v "$_a_script" "$(dirname $_a_script)/$2"
else
  echo "a_cp: $1: No such file" >&2
  return 1
fi
