#!/bin/bash
# force unmount and eject disk from volume name

if [ $# -ne 1 ]; then
  echo 'usage : eject <volume name>'
  return 1
fi

_line_count=$(df | grep $1 | wc -l)

if [ "$_line_count" -ne 1 ]; then
  echo 'error : None or too many line is searched'
  df | grep $1
  return 1
fi

_volume_device=$(df | grep $1 | awk '{print $1}')
_physical_device=$(diskutil info $_volume_device | grep "Part of Whole" | awk '{print $4}')
# physical_store=$(diskutil info $_volume_device | grep "APFS Physical Store" | awk '{print $4}')

diskutil unmountDisk $_volume_device

if [[ $? -ne 0 ]]; then
  diskutil unmountDisk force $_volume_device
fi

diskutil eject $_physical_device

unset _line_count
unset _volume_device
unset _physical_device
