#!/bin/bash
#	usage: generate_c_structure <class name> <path>

if [[ $# -eq 1 ]]; then
	2=$(pwd)
elif [[ $# -eq 2 ]]; then
	if [[ $2[1] != "/" ]]; then
		2=$(pwd)/$2
	fi
else
	echo 'usage: generateCppClass <class name> <path>'
	return 1
fi

if [[ -e $2/$1.hpp ]] || [[ -e $2/$1.cpp ]]; then
	echo "[$2/$1.hpp] or [$2/$1.cpp] is already exists!"
	return 1
fi

cd $ENVIRONMENT/.tool
echo uppercase name = $(tr '[:lower:]' '[:upper:]' <<< $1)"\n"class name = $1"\n"instance name = $(tr '[:upper:]' '[:lower:]' <<< ${1:0:1})${1:1} > name.variable

_hppfile=$2/$1.hpp
echo hppfile : $_hppfile
./variabledText.out templateClass.hpp -o $2/$1.hpp
unset _hppfile

_cppfile=$2/$1.cpp
echo cppfile : $_cppfile
./variabledText.out templateClass.cpp -o $2/$1.cpp
unset _cppfile

rm name.variable
