#!/bin/bash
# diff a commit's change

if [ $# -lt 0 ]; then
  printf "usage: %s commit [options]\n" "$(basename "$0")"
  return 1
fi



if [ -z "$1" ] || [[ "$1" == -* ]]; then
  _commit="HEAD"
else
  _commit="$1"
  shift
fi

_output=$(git diff --color=always $_commit^ $_commit "$@")
# line_count=$(echo "$_output" | wc -l)
_clean_first_line=$(echo "$_output" | head -n 1 | sed 's/\x1b\[[0-9;]*m//g')

# if [ "$line_count" -ge "$(tput lines)" ]; then
if [[ $_clean_first_line =~ ^diff ]]; then
  echo "$_output" | less -R -p "^diff"
else
  echo "$_output"
fi

unset _commit
unset _output
unset _clean_first_line
