#!/bin/bash

if [ $# -eq 0 ]; then
    git status
else
    for _repository_name in "$@"; do
        echo
        echo
        echo
        echo 'path : $personal/'"$_repository_name"
        builtin cd "$personal/$_repository_name"
        git status
    done
fi

>/dev/null cd -

unset _repository_name
