#!/bin/bash
# jump to mark in file system

if [ $# -gt 1 ]; then
  echo 'usage: jump [<mark>]'
  return 1
fi

_mark="a_mark_${1:-temp}"
eval "_a_mark_path=\$$_mark"
cd $_a_mark_path

unset _mark
unset _a_mark_path
