#!/bin/bash
# ls a_script

if [ $# -gt 1 ]; then
  echo 'usage: ls [a_script]'
  return 1
fi

if [ -n "$1" ]; then
  _is_exist=0
  for _a_path in "${a_path[@]}"; do
    if [ -f "$_a_path/$1" ]; then
      _is_exist=1
      command ls "$_a_path/$1"
    fi
  done
  if [ "$_is_exist" -eq 0 ]; then
    echo "a_ls: $1: No such file" >&2
  fi
else
  for _a_path in "${a_path[@]}"; do
    command ls "$_a_path"
  done
fi

unset _a_path
unset _is_exist
