#!/bin/bash
# generate objdump file for x86_64 from c file or assembly code or object file

if [[ $# -ne 1 ]]; then
    echo 'usage: aux objdump_x <filename>'
    return 1
fi

_basename=${1%.*}
_extension=${1##*.}

if [[ _extension == "c" || _extension == "s" ]]; then
    clang -o .$_basename.o -c $_basename.c -O1 -target x86_64-apple-macos10.12
    objdump -D -S .$_basename.o > $_basename.objdump
    rm .$_basename.o
else
    objdump -D -S $1 > $_basename.objdump
fi


unset _basename
unset _extension
