#!/bin/bash
# rm a_script

if [ $# -ne 1 ]; then
  echo 'usage: rm <a_script>'
  return 1
fi

if . "$A_CORE/_get_a_script" "$1"; then
  rm "$_a_script"
  echo "a_rm: [$1] is removed"
else
  echo "a_rm: $1: No such file" >&2
  return 1
fi
