#!/bin/bash
# todo: add user, host
# todo: replace scp to rsync

if [ $# -eq 0 ]; then
  echo 'usage: send <destination : location> [<files : path>]'
elif [ $# -eq 1 ]; then
  2=$local/send/*
fi

_networkAddress=$1
_destination=$_networkAddress:/home/a/local/receive

shift

scp -r $@ $_destination

unset _networkAddress
unset _destination
