#!/bin/bash
# vim a_script

if [ $# -ne 1 ]; then
  printf "usage : %s <%s>\n" "$(basename "$0")" "a_script"
  return 1
fi

if . "$A_CORE/_get_a_script" "$1"; then
  vim "$_a_script"
else
  cat << 'EOF' > "$A_PATH_PRIVATE/$1"
#!/bin/bash
# description

if [ $# -ne 1 ]; then
  printf "usage: %s <%s>\n" "$(basename "$0")" "arg"
  return 1
fi




EOF

  vim "$A_PATH_PRIVATE/$1"
fi
