#!/bin/bash
# vim a_script

if [ $# -ne 1 ]; then
  echo 'usage: vim <a_script>'
  return 1
fi

if . "$A_CORE/_get_a_script" "$1"; then
  vim "$_a_script"
else
  cat << 'EOF' > "$A_PATH_PRIVATE/$1"
#!/bin/bash
# description

if [ $# -ne 1 ]; then
  echo 'usage: a_script <arg>'
  return 1
fi


EOF

  vim "$A_PATH_PRIVATE/$1"
fi
