#!/bin/bash

if [[ $# -ne 1 ]]; then
	echo 'usage: vimassembly <path>'
fi

if [[ ${1##*.} == "c" ]]; then
	_baseName=${1%.c}
	clang -c -g $1 && objdump -l -S $_baseName.o > $_baseName.s && vim $_baseName.s
elif [[ ${1##*.} == "cpp" ]]; then
	_baseName=${1%.cpp}
	clang++ -c -g $1 && objdump -l -S $_baseName.o > $_baseName.s && vim $_baseName.s
fi

unset _baseName

# if [[ ${1##*.} == "c" ]]; then
# 	clang -S $1 && vim ${1%.c}.s
# elif [[ ${1##*.} == "cpp" ]]; then
# 	clang++ -S $1 && vim ${1%.cpp}.s
# fi
