#!/bin/bash
# vim vimsession for git repository

if [ $# -ge 2 ]; then
  echo 'usage: vimvs [<vim session name>]'
  return 1
fi

_repo_local_path=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
_vim_session_name=${1:-$(2>/dev/null basename "$_repo_local_path")}

command vim $PRIVATE/.vimsession/$_vim_session_name

unset _repo_local_path
unset _vim_session_name
