#!/bin/bash
# diff a commit's change

if [ $# -lt 0 ]; then
  printf "usage: %s commit [options]\n" "$(basename "$0")"
  exit 1
fi



if [ -z "$1" ] || [[ "$1" == -* ]]; then
  commit="HEAD"
else
  commit="$1"
  shift
fi

output=$(git diff --color=always $commit^ $commit "$@")
# line_count=$(echo "$output" | wc -l)
CLEAN_FIRST_LINE=$(echo "$output" | head -n 1 | sed 's/\x1b\[[0-9;]*m//g')

# if [ "$line_count" -ge "$(tput lines)" ]; then
if [[ $CLEAN_FIRST_LINE =~ ^diff ]]; then
  echo "$output" | less -R -p "^diff"
else
  echo "$output"
fi
