#!/bin/bash

# list a_command

if [ $# -gt 1 ]; then
  printf "usage : ls [a_command]\n"
  exit 1
fi

for p in $(echo $A_PATH | tr ':' '\n'); do
  if [ -n "$1" ]; then
    if [ -x "$p/$1" ]; then
      ls "$p/$1"
    fi
  else
    if [ -d "$p" ]; then
      ls "$p"
    fi
  fi
done
