#!/bin/bash

if [ $# -ne 1 ]; then
  echo 'usage : publish <a_command>'
  exit 1
fi

first_path=$(echo "$A_PATH" | tr ':' '\n' | sed -n '1p')
second_path=$(echo "$A_PATH" | tr ':' '\n' | sed -n '2p')

mv "$first_path/$1" "$second_path/$1"
