#!/bin/bash
# vim a_command

if [ $# -ne 1 ]; then
  printf "usage : %s <a_command>\n" "$(basename "$0")"
  return 1
fi

found=false

for p in $(echo $A_PATH | tr ':' '\n'); do
  if [ -x "$p/$1" ]; then
    found=true
    vim "$p/$1"
    break
  fi
done

if [ "$found" = false ]; then
  cat << 'EOF' > "$A_PATH_PRIVATE/$1"
#!/bin/bash
# description

if [ $# -ne 1 ]; then
  printf "usage: %s %s\n" "$(basename "$0")" "<arg>"
  return 1
fi




EOF

  chmod +x "$A_PATH_PRIVATE/$1"
  vim "$A_PATH_PRIVATE/$1"
fi

unset found
unset p
