#!/bin/bash

# vim a command

if [ $# -ne 1 ]; then
  echo 'usage : vim <a_command>'
  exit 1
fi

found=false

for p in $(echo $A_PATH | tr ':' '\n'); do
  if [ -x "$p/$1" ]; then
    cd $p
    vim "$p/$1"
    found=true
    break
  fi
done

if [ "$found" = false ]; then
  first_path=$(echo "$A_PATH" | tr ':' '\n' | head -n 1)
  cd $first_path
  vim "$first_path/$1"
fi
