#!/bin/bash

# vim a_command

if [ $# -ne 1 ]; then
  printf "usage : %s <a_command>\n" "$(basename "$0")"
  exit 1
fi

found=false

for path in $(echo $A_PATH | tr ':' '\n'); do
  if [ -x "$path/$1" ]; then
    found=true
    vim "$path/$1"
    break
  fi
done

if [ "$found" = false ]; then
  cat << 'EOF' > "$private_a_bin/$1"
#!/bin/bash
# description

if [ $# -ne 1 ]; then
  printf "usage: %s arg\n" "$(basename "$0")"
  exit 1
fi




EOF

  chmod +x "$private_a_bin/$1"
  vim "$private_a_bin/$1"
fi
